name: LibreWin Security Vulnerability Report
description: Report a security vulnerability in LibreWin.
title: "[Vuln]: "
labels: ["security", "vulnerability", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a security vulnerability in LibreWin.
        Your contribution helps enhance the security and reliability of LibreWin.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you for further information or clarification?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: vuln-description
    attributes:
      label: Vulnerability Description
      description: Provide a detailed description of the security vulnerability, including steps to reproduce.
      placeholder: Describe the vulnerability in detail.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Assess the severity of this vulnerability.
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 2
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detail the steps to reproduce the vulnerability.
      placeholder: "Step 1: ..."
    validations:
      required: true
  - type: textarea
    id: potential-impact
    attributes:
      label: Potential Impact
      description: Describe the potential consequences if this vulnerability is exploited.
      placeholder: "Exploiting this vulnerability could lead to..."
    validations:
      required: true
  - type: dropdown
    id: affected-components
    attributes:
      label: Affected Components
      description: Identify which parts of LibreWin are affected by this vulnerability.
      multiple: true
      options:
        - Kernel
        - Win32 API
        - Other
    validations:
      required: true
  - type: textarea
    id: patch-or-suggested-fix
    attributes:
      label: Patch/Suggested Fix
      description: If you have a proposed solution or patch, please provide details here.
      placeholder: "Suggested fix: ..."
    validations:
      required: false
  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Security Policy
      description: By submitting this vulnerability report, you agree to follow LibreWin's security policy.
      options:
        - label: I agree to follow LibreWin's Security Policy
          required: true

